# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    image: clinic-manager-app-backend:1.0
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      ACCESS_TOKEN_SECRET: secret
      REFRESH_TOKEN_SECRET: secret
      NODE_ENV: dev
      DATABASE_URI: "mongodb://admin:password@mongo:27017/cmadb"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local